import { Event, DanceType } from "./types";
import { Timestamp } from "firebase/firestore";

function makeDate(daysFromNow: number, hour: number): Date {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, 0, 0, 0);
  return d;
}

export const MOCK_EVENTS: Event[] = [
  {
    id: "1",
    name: "Salsa Saturdays at Echoes",
    address: "2314 Sunset Blvd, Los Angeles, CA",
    lat: 34.0763,
    lng: -118.2607,
    geohash: "9q5csw",
    dateTime: makeDate(0, 21) as unknown as Timestamp,
    danceTypes: ["salsa"],
    venueType: "club",
    floorType: "wood",
    liveMusic: true,
    coverPrice: 15,
    organizerName: "LA Salsa Scene",
    instagramLink: "https://instagram.com/lasalsascene",
    verified: true,
    verificationCount: 12,
    createdBy: "admin",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 48,
  },
  {
    id: "2",
    name: "Bachata Vibes — Clifton's",
    address: "648 S Broadway, Los Angeles, CA",
    lat: 34.0457,
    lng: -118.2524,
    geohash: "9q5crt",
    dateTime: makeDate(0, 22) as unknown as Timestamp,
    danceTypes: ["bachata", "salsa"],
    venueType: "club",
    floorType: "wood",
    liveMusic: false,
    coverPrice: 10,
    organizerName: "DTLA Dance",
    instagramLink: "https://instagram.com/dtladance",
    verified: true,
    verificationCount: 7,
    createdBy: "admin",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 31,
  },
  {
    id: "3",
    name: "Cumbia Night — El Chavo",
    address: "4550 Fountain Ave, Los Angeles, CA",
    lat: 34.0858,
    lng: -118.2928,
    geohash: "9q5csq",
    dateTime: makeDate(1, 20) as unknown as Timestamp,
    danceTypes: ["cumbia", "merengue"],
    venueType: "restaurant",
    floorType: "tile",
    liveMusic: true,
    coverPrice: 0,
    organizerName: "El Chavo LA",
    instagramLink: "https://instagram.com/elchavola",
    verified: false,
    verificationCount: 2,
    createdBy: "user1",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 14,
  },
  {
    id: "4",
    name: "Latin Night — Avalon Hollywood",
    address: "1735 N Vine St, Hollywood, CA",
    lat: 34.1009,
    lng: -118.3271,
    geohash: "9q5cs2",
    dateTime: makeDate(2, 22) as unknown as Timestamp,
    danceTypes: ["salsa", "bachata", "merengue"],
    venueType: "club",
    floorType: "wood",
    liveMusic: false,
    coverPrice: 25,
    organizerName: "Avalon Hollywood",
    instagramLink: "https://instagram.com/avalonhollywood",
    verified: true,
    verificationCount: 20,
    createdBy: "admin",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 112,
  },
  {
    id: "5",
    name: "Bachata Social — Koreatown",
    address: "3339 W 8th St, Los Angeles, CA",
    lat: 34.0567,
    lng: -118.3049,
    geohash: "9q5csh",
    dateTime: makeDate(1, 19) as unknown as Timestamp,
    danceTypes: ["bachata"],
    venueType: "restaurant",
    floorType: "tile",
    liveMusic: false,
    coverPrice: 5,
    organizerName: "Ktown Dance Crew",
    instagramLink: "https://instagram.com/ktowndance",
    verified: false,
    verificationCount: 1,
    createdBy: "user2",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 8,
  },
  {
    id: "6",
    name: "Merengue & Cumbia House Party",
    address: "2048 Griffith Park Blvd, Los Angeles, CA",
    lat: 34.0967,
    lng: -118.2614,
    geohash: "9q5ct3",
    dateTime: makeDate(3, 20) as unknown as Timestamp,
    danceTypes: ["merengue", "cumbia"],
    venueType: "house_party",
    floorType: "wood",
    liveMusic: false,
    coverPrice: 0,
    organizerName: "Silver Lake Socials",
    instagramLink: "",
    verified: false,
    verificationCount: 0,
    createdBy: "user3",
    createdAt: new Date() as unknown as Timestamp,
    goingCount: 22,
  },
];
